services:
  postgres:
    container_name: soa_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: khaled
      POSTGRES_PASSWORD: khaled
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432  # Change this line
    restart: unless-stopped

volumes:
  postgres:
